# -*- coding: utf-8 -*-
"""SMS_Spam_Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbPv8zVo2UHzcmoAfrUQP787Nurkltc8
"""

!pip install ucimlrepo joblib

"""# ===================================================
# PHASE 1: DATASET LOADING
# ===================================================
"""

# =========================================================
# PHASE 1: DATASET LOADING (Fixed - direct download method)
# =========================================================

# ---- Import required libraries ----
import pandas as pd
import numpy as np
import requests
import zipfile
import io

# ---- Load the SMS Spam Collection dataset directly from UCI ----
def load_sms_dataset() -> pd.DataFrame:
    """
    Downloads the SMS Spam Collection dataset directly from the UCI
    static file server (bypasses ucimlrepo, which doesn't yet support
    this dataset's newer API format) and returns it as a DataFrame.

    Returns:
        pd.DataFrame: Raw SMS dataset with columns ['label', 'message']
    """
    url = "https://archive.ics.uci.edu/static/public/228/sms+spam+collection.zip"

    # Download the zip file into memory
    response = requests.get(url)
    response.raise_for_status()  # raises an error if download failed

    # Open the zip in memory and extract the data file
    with zipfile.ZipFile(io.BytesIO(response.content)) as z:
        with z.open("SMSSpamCollection") as f:
            df = pd.read_csv(f, sep="\t", header=None, names=["label", "message"])

    return df


# ---- Load the data ----
df = load_sms_dataset()

# ---- Display first five rows ----
print("First 5 rows of the dataset:")
print(df.head())

# ---- Dataset shape ----
print(f"\nDataset shape: {df.shape}")
print(f"Number of messages: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

# ---- Dataset information (data types, non-null counts) ----
print("\nDataset info:")
df.info()

# ---- Dataset statistics ----
print("\nDataset statistics (categorical summary):")
print(df.describe())

"""# ===================================================
# PHASE 2: DATASET CLEANING
# ===================================================
"""

# =========================================================
# PHASE 2: DATASET CLEANING
# =========================================================

# ---- Step 1: Missing value analysis ----
print("Missing values per column (before cleaning):")
print(df.isnull().sum())

# ---- Step 2: Duplicate check and removal ----
print(f"\nTotal rows before duplicate removal: {df.shape[0]}")
print(f"Number of duplicate rows: {df.duplicated().sum()}")

# Remove duplicates, keeping the first occurrence
df = df.drop_duplicates(keep="first").reset_index(drop=True)

print(f"Total rows after duplicate removal: {df.shape[0]}")

# ---- Step 3: Label encoding (spam=1, ham=0) ----
def encode_labels(df: pd.DataFrame) -> pd.DataFrame:
    """
    Encodes the 'label' column into a new numeric column 'label_num'.
    spam -> 1, ham -> 0

    Args:
        df (pd.DataFrame): DataFrame with a 'label' column containing 'spam'/'ham'

    Returns:
        pd.DataFrame: Same DataFrame with an added 'label_num' column
    """
    df["label_num"] = df["label"].map({"spam": 1, "ham": 0})
    return df

df = encode_labels(df)

# ---- Step 4: Before/after statistics ----
print("\nClass distribution after cleaning:")
print(df["label"].value_counts())

print("\nClass proportion after cleaning:")
print(df["label"].value_counts(normalize=True))

print("\nFirst 5 rows after cleaning and encoding:")
print(df.head())

print(f"\nFinal dataset shape: {df.shape}")

"""# ===================================================
# PHASE 3: EXPLORATORY DATA ANALYSIS
# ===================================================
"""

# =========================================================
# PHASE 3: EXPLORATORY DATA ANALYSIS
# =========================================================
import matplotlib.pyplot as plt

# ---- Step 1: Class distribution counts ----
class_counts = df["label"].value_counts()
print("Class counts:")
print(class_counts)

# ---- Step 2: Bar chart - Spam vs Ham count ----
def plot_class_bar_chart(counts: pd.Series) -> None:
    """
    Plots a bar chart showing the count of spam vs ham messages.

    Args:
        counts (pd.Series): value_counts() output of the 'label' column
    """
    plt.figure(figsize=(6, 5))
    bars = plt.bar(counts.index, counts.values, color=["#4CAF50", "#F44336"])

    plt.title("Spam vs Ham Message Count", fontsize=14, fontweight="bold")
    plt.xlabel("Message Type")
    plt.ylabel("Number of Messages")
    plt.grid(axis="y", linestyle="--", alpha=0.6)

    # Add value labels on top of bars
    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width() / 2, height + 30,
                  str(height), ha="center", fontweight="bold")

    plt.tight_layout()
    plt.show()

plot_class_bar_chart(class_counts)

# ---- Step 3: Pie chart - class proportion ----
def plot_class_pie_chart(counts: pd.Series) -> None:
    """
    Plots a pie chart showing the proportion of spam vs ham messages.

    Args:
        counts (pd.Series): value_counts() output of the 'label' column
    """
    plt.figure(figsize=(6, 6))
    plt.pie(counts.values, labels=counts.index, autopct="%1.2f%%",
            colors=["#4CAF50", "#F44336"], startangle=90,
            explode=(0, 0.05))  # slightly pull out the spam slice

    plt.title("Class Proportion: Spam vs Ham", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.show()

plot_class_pie_chart(class_counts)

# ---- Step 4: Message length column ----
df["message_length"] = df["message"].apply(len)

print("\nMessage length statistics by class:")
print(df.groupby("label")["message_length"].describe())

# ---- Step 5: Message length histogram ----
def plot_length_histogram(df: pd.DataFrame) -> None:
    """
    Plots overlapping histograms of message length, split by class.

    Args:
        df (pd.DataFrame): DataFrame containing 'message_length' and 'label'
    """
    plt.figure(figsize=(8, 5))
    plt.hist(df[df["label"] == "ham"]["message_length"], bins=40,
              alpha=0.6, label="Ham", color="#4CAF50")
    plt.hist(df[df["label"] == "spam"]["message_length"], bins=40,
              alpha=0.6, label="Spam", color="#F44336")

    plt.title("Message Length Distribution: Spam vs Ham", fontsize=14, fontweight="bold")
    plt.xlabel("Message Length (characters)")
    plt.ylabel("Frequency")
    plt.legend()
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.tight_layout()
    plt.show()

plot_length_histogram(df)

# ---- Step 6: Box plot of message length by class ----
def plot_length_boxplot(df: pd.DataFrame) -> None:
    """
    Plots a box plot comparing message length distributions for spam vs ham.

    Args:
        df (pd.DataFrame): DataFrame containing 'message_length' and 'label'
    """
    plt.figure(figsize=(6, 5))
    data_to_plot = [df[df["label"] == "ham"]["message_length"],
                     df[df["label"] == "spam"]["message_length"]]

    box = plt.boxplot(data_to_plot, labels=["Ham", "Spam"], patch_artist=True)
    colors = ["#4CAF50", "#F44336"]
    for patch, color in zip(box["boxes"], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.6)

    plt.title("Message Length Box Plot: Spam vs Ham", fontsize=14, fontweight="bold")
    plt.ylabel("Message Length (characters)")
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.tight_layout()
    plt.show()

plot_length_boxplot(df)

# ---- Step 7: Word frequency analysis ----
import re
from collections import Counter

def get_word_frequency(messages: pd.Series, top_n: int = 15) -> list:
    """
    Extracts the most common words from a series of messages.

    Args:
        messages (pd.Series): Series of raw text messages
        top_n (int): Number of top words to return

    Returns:
        list: List of (word, count) tuples
    """
    all_words = []
    for msg in messages:
        words = re.findall(r"\b[a-z]+\b", msg.lower())  # extract lowercase words only
        all_words.extend(words)
    return Counter(all_words).most_common(top_n)

spam_word_freq = get_word_frequency(df[df["label"] == "spam"]["message"])
ham_word_freq = get_word_frequency(df[df["label"] == "ham"]["message"])

print("\nTop 15 words in SPAM messages:")
for word, count in spam_word_freq:
    print(f"  {word}: {count}")

print("\nTop 15 words in HAM messages:")
for word, count in ham_word_freq:
    print(f"  {word}: {count}")

# ---- Step 8: Bar chart for spam word frequency ----
def plot_word_frequency(word_freq: list, title: str, color: str) -> None:
    """
    Plots a horizontal bar chart of top word frequencies.

    Args:
        word_freq (list): List of (word, count) tuples
        title (str): Chart title
        color (str): Bar color
    """
    words, counts = zip(*word_freq)
    plt.figure(figsize=(8, 6))
    plt.barh(words, counts, color=color)
    plt.title(title, fontsize=14, fontweight="bold")
    plt.xlabel("Frequency")
    plt.ylabel("Word")
    plt.grid(axis="x", linestyle="--", alpha=0.6)
    plt.gca().invert_yaxis()  # highest frequency on top
    plt.tight_layout()
    plt.show()

plot_word_frequency(spam_word_freq, "Top 15 Words in Spam Messages", "#F44336")
plot_word_frequency(ham_word_freq, "Top 15 Words in Ham Messages", "#4CAF50")

"""# ===================================================
# PHASE 4: PROBABILITY ANALYSIS
# ===================================================
"""

# =========================================================
# PHASE 4: PROBABILITY ANALYSIS
# =========================================================

# ---- Step 1: Prior probabilities ----
total_messages = len(df)
total_spam = (df["label"] == "spam").sum()
total_ham = (df["label"] == "ham").sum()

P_spam = total_spam / total_messages
P_ham = total_ham / total_messages

print("=== PRIOR PROBABILITIES ===")
print(f"P(Spam) = {total_spam} / {total_messages} = {P_spam:.4f}")
print(f"P(Ham)  = {total_ham} / {total_messages} = {P_ham:.4f}")
print(f"Check: P(Spam) + P(Ham) = {P_spam + P_ham:.4f}  (should be 1.0)")


# ---- Step 2: Conditional probability - direct (empirical) method ----
def direct_conditional_probability(df: pd.DataFrame, word: str) -> dict:
    """
    Calculates P(Spam | word) directly using frequency counts:
    (messages with word AND spam) / (messages with word)

    Args:
        df (pd.DataFrame): Cleaned dataset with 'label' and 'message' columns
        word (str): The word to search for (case-insensitive, whole word match)

    Returns:
        dict: Contains counts and the calculated P(Spam | word)
    """
    # Build a boolean mask: does the message contain this word (whole word, case-insensitive)?
    pattern = r"\b" + re.escape(word) + r"\b"
    contains_word = df["message"].str.contains(pattern, case=False, regex=True)

    total_with_word = contains_word.sum()
    spam_with_word = (contains_word & (df["label"] == "spam")).sum()

    p_spam_given_word = spam_with_word / total_with_word if total_with_word > 0 else 0.0

    return {
        "word": word,
        "total_with_word": total_with_word,
        "spam_with_word": spam_with_word,
        "P_spam_given_word_direct": p_spam_given_word
    }


# ---- Step 3: Conditional probability - Bayes' Theorem method ----
def bayes_conditional_probability(df: pd.DataFrame, word: str, P_spam: float, P_ham: float) -> dict:
    """
    Calculates P(Spam | word) using Bayes' Theorem:
    P(Spam|Word) = [P(Word|Spam) * P(Spam)] / P(Word)

    Args:
        df (pd.DataFrame): Cleaned dataset
        word (str): The word to search for
        P_spam (float): Prior probability of spam
        P_ham (float): Prior probability of ham

    Returns:
        dict: Contains intermediate probabilities and the final P(Spam | word)
    """
    pattern = r"\b" + re.escape(word) + r"\b"
    contains_word = df["message"].str.contains(pattern, case=False, regex=True)

    spam_msgs = df[df["label"] == "spam"]
    ham_msgs = df[df["label"] == "ham"]

    # P(Word | Spam): fraction of spam messages containing the word
    word_in_spam = contains_word[df["label"] == "spam"].sum()
    P_word_given_spam = word_in_spam / len(spam_msgs)

    # P(Word | Ham): fraction of ham messages containing the word
    word_in_ham = contains_word[df["label"] == "ham"].sum()
    P_word_given_ham = word_in_ham / len(ham_msgs)

    # P(Word): law of total probability
    P_word = (P_word_given_spam * P_spam) + (P_word_given_ham * P_ham)

    # Bayes' Theorem
    P_spam_given_word = (P_word_given_spam * P_spam) / P_word if P_word > 0 else 0.0

    return {
        "word": word,
        "P_word_given_spam": P_word_given_spam,
        "P_word_given_ham": P_word_given_ham,
        "P_word": P_word,
        "P_spam_given_word_bayes": P_spam_given_word
    }


# ---- Step 4: Run analysis for all five suspicious words ----
suspicious_words = ["free", "prize", "win", "urgent", "offer"]

print("\n\n=== CONDITIONAL PROBABILITY ANALYSIS (5 words) ===\n")

results = []
for word in suspicious_words:
    direct = direct_conditional_probability(df, word)
    bayes = bayes_conditional_probability(df, word, P_spam, P_ham)

    print(f"--- Word: '{word}' ---")
    print(f"  Messages containing '{word}': {direct['total_with_word']}")
    print(f"  Of which spam: {direct['spam_with_word']}")
    print(f"  Direct  P(Spam | '{word}') = {direct['P_spam_given_word_direct']:.4f}")
    print(f"  Bayes'  P('{word}' | Spam) = {bayes['P_word_given_spam']:.4f}")
    print(f"  Bayes'  P('{word}' | Ham)  = {bayes['P_word_given_ham']:.4f}")
    print(f"  Bayes'  P('{word}')        = {bayes['P_word']:.4f}")
    print(f"  Bayes'  P(Spam | '{word}') = {bayes['P_spam_given_word_bayes']:.4f}")

    match = abs(direct['P_spam_given_word_direct'] - bayes['P_spam_given_word_bayes']) < 1e-9
    print(f"  ✓ Direct and Bayes' results match: {match}\n")

    results.append({
        "word": word,
        "direct": direct['P_spam_given_word_direct'],
        "bayes": bayes['P_spam_given_word_bayes']
    })

# ---- Step 5: Summary table ----
summary_df = pd.DataFrame(results)
summary_df.columns = ["Word", "P(Spam|Word) - Direct", "P(Spam|Word) - Bayes"]
print("=== SUMMARY TABLE ===")
print(summary_df.to_string(index=False))

"""# ===================================================
# PHASE 5: RANDOM VARIABLE ANALYSIS
# ===================================================
"""

# =========================================================
# PHASE 5: RANDOM VARIABLE ANALYSIS
# =========================================================

# ---- Step 1: Define the Bernoulli random variable ----
# Y = 1 if Spam, Y = 0 if Ham
# This is already represented by our 'label_num' column from Phase 2
Y = df["label_num"]

print("=== BERNOULLI RANDOM VARIABLE: Y ===")
print("Y = 1 -> Spam, Y = 0 -> Ham")
print(f"\nFirst 10 values of Y:\n{Y.head(10).values}")
print(f"\nTotal observations: {len(Y)}")

# ---- Step 2: Calculate p = P(Spam) ----
p = Y.mean()  # mean of a 0/1 column = proportion of 1s = P(Spam)
print(f"\np = P(Spam) = {p:.4f}")

# ---- Step 3: Expectation E(Y) ----
def calculate_expectation(Y: pd.Series) -> float:
    """
    Calculates the expectation E(Y) of a Bernoulli random variable.
    For Bernoulli, E(Y) = p = mean of Y.

    Args:
        Y (pd.Series): Series of 0/1 values

    Returns:
        float: E(Y)
    """
    return Y.mean()

E_Y = calculate_expectation(Y)
print(f"\n=== EXPECTATION ===")
print(f"E(Y) = mean(Y) = {E_Y:.4f}")
print(f"Compare to P(Spam) from Phase 4: {P_spam:.4f}")
print(f"Match: {np.isclose(E_Y, P_spam)}")

# ---- Step 4: Variance Var(Y) ----
def calculate_variance(p: float) -> float:
    """
    Calculates the theoretical variance of a Bernoulli random variable.
    Var(Y) = p * (1 - p)

    Args:
        p (float): Probability of success (spam)

    Returns:
        float: Var(Y)
    """
    return p * (1 - p)

Var_Y_formula = calculate_variance(p)
Var_Y_pandas = Y.var(ddof=0)  # population variance, for direct comparison to the formula

print(f"\n=== VARIANCE ===")
print(f"Var(Y) using formula p(1-p) = {p:.4f} * {1-p:.4f} = {Var_Y_formula:.4f}")
print(f"Var(Y) using pandas .var()  = {Var_Y_pandas:.4f}")
print(f"Match: {np.isclose(Var_Y_formula, Var_Y_pandas)}")

# ---- Step 5: Standard deviation (bonus - useful for interpretation) ----
Std_Y = np.sqrt(Var_Y_formula)
print(f"\nStandard Deviation SD(Y) = sqrt(Var(Y)) = {Std_Y:.4f}")

# ---- Step 6: Interpretation summary ----
print("\n=== INTERPRETATION ===")
print(f"E(Y) = {E_Y:.4f} -> On average, about {E_Y*100:.1f}% of messages are spam.")
print(f"Var(Y) = {Var_Y_formula:.4f} -> Relatively low variance, since p is far from 0.5,")
print(f"          meaning the outcome (spam/ham) is fairly predictable in aggregate")
print(f"          (most messages are ham).")

"""# ===================================================
# PHASE 6: FEATURE ENGINEERING
# ===================================================
"""

# =========================================================
# PHASE 6: FEATURE ENGINEERING
# =========================================================
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# ---- Step 1: Define features (X) and target (y) ----
X = df["message"]        # raw text messages
y = df["label_num"]      # 0 = ham, 1 = spam

# ---- Step 2: Train-test split with stratified sampling ----
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,       # 80% train, 20% test
    random_state=42,      # for reproducibility
    stratify=y            # preserves the spam/ham ratio in both sets
)

print("=== TRAIN-TEST SPLIT ===")
print(f"Training set size: {len(X_train)} messages")
print(f"Testing set size:  {len(X_test)} messages")

print(f"\nTraining set class distribution:")
print(y_train.value_counts(normalize=True))

print(f"\nTesting set class distribution:")
print(y_test.value_counts(normalize=True))

# ---- Step 3: Apply CountVectorizer ----
def build_vectorizer_and_transform(X_train: pd.Series, X_test: pd.Series):
    """
    Fits a CountVectorizer on training text and transforms both
    training and test sets into numeric sparse matrices.

    Args:
        X_train (pd.Series): Raw training messages
        X_test (pd.Series): Raw test messages

    Returns:
        tuple: (vectorizer, X_train_vec, X_test_vec)
    """
    vectorizer = CountVectorizer()

    # Fit ONLY on training data, then transform training data
    X_train_vec = vectorizer.fit_transform(X_train)

    # Transform test data using the SAME fitted vocabulary (no re-fitting!)
    X_test_vec = vectorizer.transform(X_test)

    return vectorizer, X_train_vec, X_test_vec

vectorizer, X_train_vec, X_test_vec = build_vectorizer_and_transform(X_train, X_test)

# ---- Step 4: Inspect vocabulary and matrix dimensions ----
vocab_size = len(vectorizer.vocabulary_)
print(f"\n=== VECTORIZATION RESULTS ===")
print(f"Vocabulary size: {vocab_size} unique words")

print(f"\nSparse matrix dimensions:")
print(f"  X_train_vec shape: {X_train_vec.shape}  (messages x vocabulary)")
print(f"  X_test_vec shape:  {X_test_vec.shape}")

# ---- Step 5: Sparsity check ----
non_zero = X_train_vec.nnz
total_cells = X_train_vec.shape[0] * X_train_vec.shape[1]
sparsity = 1 - (non_zero / total_cells)
print(f"\nMatrix sparsity: {sparsity:.4%} of cells are zero")
print(f"(This is expected -- each message only uses a tiny fraction of the full vocabulary)")

# ---- Step 6: Show top features (first 20 vocabulary words alphabetically) ----
feature_names = vectorizer.get_feature_names_out()
print(f"\nFirst 20 features in vocabulary (alphabetical):")
print(feature_names[:20])

# ---- Step 7: Most frequent words overall (by total count across training set) ----
word_counts = np.asarray(X_train_vec.sum(axis=0)).flatten()
top_indices = word_counts.argsort()[-15:][::-1]
print(f"\nTop 15 most frequent words in training vocabulary:")
for idx in top_indices:
    print(f"  {feature_names[idx]}: {word_counts[idx]}")

"""# ======================================================
# PHASE 7: MACHINE LEARNING MODEL - MULTINOMIAL NAIVE BAYES
# ======================================================
"""

# =========================================================
# PHASE 7: MACHINE LEARNING MODEL - MULTINOMIAL NAIVE BAYES
# =========================================================
from sklearn.naive_bayes import MultinomialNB

# ---- Step 1: Initialize the model ----
# alpha=1.0 applies Laplace smoothing (default, prevents zero-probability issue)
model = MultinomialNB(alpha=1.0)

# ---- Step 2: Train the model ----
def train_naive_bayes(model: MultinomialNB, X_train_vec, y_train: pd.Series) -> MultinomialNB:
    """
    Trains a Multinomial Naive Bayes model on vectorized training data.

    Args:
        model (MultinomialNB): An initialized (untrained) MultinomialNB instance
        X_train_vec: Sparse matrix of training features (from CountVectorizer)
        y_train (pd.Series): Training labels (0=ham, 1=spam)

    Returns:
        MultinomialNB: The trained model
    """
    model.fit(X_train_vec, y_train)
    return model

model = train_naive_bayes(model, X_train_vec, y_train)

print("=== MODEL TRAINING COMPLETE ===")
print(f"Model type: {type(model).__name__}")
print(f"Smoothing parameter (alpha): {model.alpha}")
print(f"Classes learned: {model.classes_}  (0=Ham, 1=Spam)")

# ---- Step 3: Inspect learned class log-priors ----
# These correspond to log(P(Ham)) and log(P(Spam)) learned from training data
class_priors = np.exp(model.class_log_prior_)
print(f"\nLearned class priors (should closely match our Phase 4/5 P(Spam), P(Ham)):")
for cls, prior in zip(model.classes_, class_priors):
    label = "Ham" if cls == 0 else "Spam"
    print(f"  P({label}) learned by model = {prior:.4f}")

# ---- Step 4: Quick sanity check - training accuracy ----
train_accuracy = model.score(X_train_vec, y_train)
print(f"\nTraining set accuracy: {train_accuracy:.4f}")
print("(Note: this is NOT our real evaluation -- just a sanity check that training worked.")
print(" True evaluation happens in Phase 8, on the unseen test set.)")

# ---- Step 5: Demonstrate Laplace smoothing effect on an example word ----
# Pick a word from our suspicious list to show smoothed probability estimates
example_word = "free"
if example_word in vectorizer.vocabulary_:
    word_idx = vectorizer.vocabulary_[example_word]
    # feature_log_prob_ gives log P(word | class) after smoothing
    log_prob_ham = model.feature_log_prob_[0][word_idx]
    log_prob_spam = model.feature_log_prob_[1][word_idx]
    print(f"\n=== Laplace-Smoothed Probabilities for '{example_word}' ===")
    print(f"  P('{example_word}' | Ham)  = {np.exp(log_prob_ham):.5f}")
    print(f"  P('{example_word}' | Spam) = {np.exp(log_prob_spam):.5f}")
    print(f"  (Compare to our manual Phase 4 calculation: P(free|Spam)=0.2266, P(free|Ham)=0.0122)")
    print(f"  Small differences are expected -- smoothing adjusts slightly, and Phase 4 used whole-word")
    print(f"  regex matching on raw text, while CountVectorizer tokenizes differently.)")

"""# ======================================================
# PHASE 8: MODEL EVALUATION
# ======================================================
"""

# =========================================================
# PHASE 8: MODEL EVALUATION
# =========================================================
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                               f1_score, confusion_matrix, classification_report)

# ---- Step 1: Generate predictions on the TEST set ----
y_pred = model.predict(X_test_vec)

# ---- Step 2: Core metrics ----
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("=== EVALUATION METRICS (on unseen TEST set) ===")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-Score:  {f1:.4f}")

# ---- Step 3: Confusion matrix ----
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()

print(f"\n=== CONFUSION MATRIX ===")
print(cm)
print(f"\nTrue Negatives (Ham correctly identified):  {tn}")
print(f"False Positives (Ham wrongly flagged Spam): {fp}  <- worse error type")
print(f"False Negatives (Spam that slipped through): {fn}")
print(f"True Positives (Spam correctly identified): {tp}")

# ---- Step 4: Full classification report ----
print(f"\n=== CLASSIFICATION REPORT ===")
print(classification_report(y_test, y_pred, target_names=["Ham", "Spam"]))

# ---- Step 5: Confusion matrix heatmap ----
def plot_confusion_matrix(cm: np.ndarray) -> None:
    """
    Plots a heatmap of the confusion matrix using matplotlib.

    Args:
        cm (np.ndarray): 2x2 confusion matrix array
    """
    plt.figure(figsize=(6, 5))
    plt.imshow(cm, cmap="Blues")
    plt.title("Confusion Matrix: Spam Detection", fontsize=14, fontweight="bold")
    plt.colorbar()

    labels = ["Ham", "Spam"]
    plt.xticks([0, 1], labels)
    plt.yticks([0, 1], labels)
    plt.xlabel("Predicted Label")
    plt.ylabel("Actual Label")

    # Annotate each cell with its count
    thresh = cm.max() / 2
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, format(cm[i, j], "d"),
                      ha="center", va="center",
                      color="white" if cm[i, j] > thresh else "black",
                      fontsize=14, fontweight="bold")

    plt.tight_layout()
    plt.show()

plot_confusion_matrix(cm)

# ---- Step 6: Interpretation ----
print("\n=== INTERPRETATION ===")
print(f"Out of {tn + fp} actual Ham messages, {fp} were wrongly flagged as Spam ({fp/(tn+fp)*100:.2f}%).")
print(f"Out of {fn + tp} actual Spam messages, {fn} slipped through as Ham ({fn/(fn+tp)*100:.2f}%).")
print(f"\nPrecision ({precision:.4f}) tells us: of all messages the model called 'Spam',")
print(f"  {precision*100:.1f}% actually were spam.")
print(f"Recall ({recall:.4f}) tells us: of all real Spam messages, the model caught {recall*100:.1f}% of them.")

"""# ======================================================
# PHASE 9: REAL-TIME PREDICTION
# ======================================================
"""

# =========================================================
# PHASE 9: REAL-TIME PREDICTION
# =========================================================

def predict_sms(message: str, model: MultinomialNB = model,
                 vectorizer: CountVectorizer = vectorizer) -> dict:
    """
    Predicts whether a given SMS message is Spam or Ham, along with
    the model's confidence (probability) for each class.

    Args:
        message (str): Raw SMS text to classify
        model (MultinomialNB): Trained Naive Bayes model (defaults to our Phase 7 model)
        vectorizer (CountVectorizer): Fitted vectorizer (defaults to our Phase 6 vectorizer)

    Returns:
        dict: Contains the prediction label and both class probabilities
    """
    if not isinstance(message, str) or message.strip() == "":
        raise ValueError("Message must be a non-empty string.")

    # Vectorize the new message using the ALREADY FITTED vectorizer
    # (must be a list, since transform() expects an iterable of documents)
    message_vec = vectorizer.transform([message])

    # Predict class (0 = Ham, 1 = Spam)
    prediction = model.predict(message_vec)[0]

    # Predict probabilities: returns [P(Ham), P(Spam)]
    probabilities = model.predict_proba(message_vec)[0]
    p_ham, p_spam = probabilities[0], probabilities[1]

    label = "Spam" if prediction == 1 else "Ham"

    return {
        "message": message,
        "prediction": label,
        "P(Spam)": round(p_spam, 4),
        "P(Ham)": round(p_ham, 4)
    }


def display_prediction(result: dict) -> None:
    """
    Nicely prints a prediction result dictionary.

    Args:
        result (dict): Output from predict_sms()
    """
    print(f"Message: \"{result['message']}\"")
    print(f"Prediction: {result['prediction']}")
    print(f"  P(Spam) = {result['P(Spam)']}")
    print(f"  P(Ham)  = {result['P(Ham)']}")
    print("-" * 60)


# ---- Test with the example from the project brief ----
test_messages = [
    "Congratulations! You won a free prize. Claim now.",
    "Free entry into our contest.",
    "Hey, are we still meeting for lunch tomorrow?",
    "URGENT! Your account has been suspended, click here to verify.",
    "Can you pick up some milk on your way home?"
]

print("=== REAL-TIME PREDICTIONS ===\n")
for msg in test_messages:
    result = predict_sms(msg)
    display_prediction(result)

# ---- Interactive input (optional - run this cell to type your own message) ----
user_message = input("Enter an SMS message to classify: ")
result = predict_sms(user_message)
print()
display_prediction(result)

"""# ======================================================
# PHASE 10: MODEL SAVING
# ======================================================
"""

# =========================================================
# PHASE 10: MODEL SAVING
# =========================================================
import joblib

# ---- Step 1: Save the trained model ----
model_filename = "sms_spam_detection_model.pkl"
joblib.dump(model, model_filename)
print(f"Model saved as: {model_filename}")

# ---- Step 2: Save the fitted vectorizer ----
vectorizer_filename = "vectorizer.pkl"
joblib.dump(vectorizer, vectorizer_filename)
print(f"Vectorizer saved as: {vectorizer_filename}")

# ---- Step 3: Verify by reloading and testing ----
def load_and_test(model_path: str, vectorizer_path: str, test_message: str) -> dict:
    """
    Loads a saved model and vectorizer from disk, then runs a test
    prediction to confirm they work correctly after reloading.

    Args:
        model_path (str): Path to the saved model .pkl file
        vectorizer_path (str): Path to the saved vectorizer .pkl file
        test_message (str): A message to test the reloaded pipeline with

    Returns:
        dict: Prediction result using the reloaded model/vectorizer
    """
    loaded_model = joblib.load(model_path)
    loaded_vectorizer = joblib.load(vectorizer_path)

    return predict_sms(test_message, model=loaded_model, vectorizer=loaded_vectorizer)

print("\n=== VERIFYING RELOADED MODEL ===")
test_result = load_and_test(model_filename, vectorizer_filename,
                              "Free entry into our contest.")
display_prediction(test_result)

# ---- Step 4: Confirm files exist on disk ----
import os
print("Files saved in current directory:")
for f in [model_filename, vectorizer_filename]:
    size_kb = os.path.getsize(f) / 1024
    print(f"  {f} — {size_kb:.2f} KB")

# ---- Step 5: Download files to your local machine (Colab-specific) ----
from google.colab import files
files.download(model_filename)
files.download(vectorizer_filename)

